name: Apply Production

on:
  push:
    branches:
      - main

jobs:
  apply:
    environment: pr
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_BUCKET_NAME: tf-state-challenge-ad
      TF_STATE_FILE_NAME: infra.tfstate
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.13.5
      - name: terraform init
        id: init
        run: |
          terraform init \
            -input=false \
            -backend-config="bucket=$TF_BUCKET_NAME" \
            -backend-config="key=$TF_STATE_FILE_NAME" \
            -backend-config="region=us-east-1" \
            -backend-config="encrypt=true"
      - name: setup aws-cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: terraform apply
        id: apply
        run: terraform apply -input=false -compact-warnings -var-file=pr.tfvars -auto-approve
